# Generated by Django 4.2.25 on 2026-03-12 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=64, null=True)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('region_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('province', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('last_region_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('level', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, db_column='parent_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='users.region', to_field='code')),
            ],
            options={
                'db_table': 'regions',
            },
        ),
    ]
