# Generated by Django 4.2.25 on 2026-03-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='localuser',
            index=models.Index(fields=['province', 'city'], name='users_provinc_b7aaa7_idx'),
        ),
        migrations.AddIndex(
            model_name='localuser',
            index=models.Index(fields=['created_at'], name='users_created_6541e9_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['parent', 'level'], name='regions_parent__d4a6d5_idx'),
        ),
    ]
