# Generated by Django 4.2.25 on 2026-03-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_localuser_users_provinc_b7aaa7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localuser',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='localuser',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
