# Generated by Django 4.2.25 on 2026-03-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_localuser_password_hash_localuser_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="localuser",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="localuser",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
