# Generated by Django 4.2.25 on 2026-03-15 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_localuser_latitude_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferenceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor_vector', models.JSONField(default=list)),
                ('category_weights', models.JSONField(default=dict)),
                ('region_weights', models.JSONField(default=dict)),
                ('exchange_completed_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference_snapshot', to='users.localuser')),
            ],
            options={
                'db_table': 'user_preference_snapshots',
            },
        ),
    ]
