# Generated by Django 4.2.25 on 2026-07-31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userpreferencesnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token_hash', models.CharField(max_length=64, unique=True)),
                ('access_expires_at', models.DateTimeField(db_index=True)),
                ('refresh_expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('device_label', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to='users.localuser')),
            ],
            options={
                'db_table': 'auth_sessions',
                'indexes': [models.Index(fields=['user', 'revoked_at', '-created_at'], name='auth_sessio_user_id_27cdaa_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuthRefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_credentials', to='users.authsession')),
                ('successor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predecessor', to='users.authrefreshtoken')),
            ],
            options={
                'db_table': 'auth_refresh_tokens',
                'indexes': [models.Index(fields=['session', 'used_at', '-created_at'], name='auth_refres_session_9b69e5_idx')],
            },
        ),
    ]
