# Generated by Django 4.2.25 on 2026-03-12 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('eat_method', models.TextField(blank=True, null=True)),
                ('images', models.JSONField(default=list)),
                ('category', models.CharField(max_length=32)),
                ('season', models.CharField(max_length=32)),
                ('shelf_life', models.CharField(max_length=32)),
                ('portability', models.CharField(max_length=32)),
                ('province', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('region_code', models.CharField(db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.localuser')),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
