# Generated by Django 4.2.25 on 2026-03-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category', 'created_at'], name='items_categor_22f66e_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['season', 'created_at'], name='items_season_143410_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['user', 'created_at'], name='items_user_id_1452f8_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['region_code', 'created_at'], name='items_region__4d3f04_idx'),
        ),
    ]
