# Generated by Django 4.2.25 on 2026-03-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_items_categor_22f66e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='audit_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='audit_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='item',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_visible', 'audit_status', 'created_at'], name='items_is_visi_24395c_idx'),
        ),
    ]
