# Generated by Django 5.2.12 on 2026-08-21 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_audit_reason_item_audit_status_item_is_visible_and_more'),
        ('users', '0006_authsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_records', to='items.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_favorites', to='users.localuser')),
            ],
            options={
                'db_table': 'item_favorites',
                'indexes': [models.Index(fields=['user', '-created_at'], name='item_favori_user_id_0d50e7_idx'), models.Index(fields=['item', 'user'], name='item_favori_item_id_b1111e_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'item'), name='unique_item_favorite')],
            },
        ),
    ]
