# Generated by Django 4.2.25 on 2026-03-12 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlavorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=64)),
                ('vote_count', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavor_tags', to='items.item')),
            ],
            options={
                'db_table': 'flavor_tags',
            },
        ),
        migrations.CreateModel(
            name='FlavorVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_votes', to='interactions.flavortag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavor_votes', to='users.localuser')),
            ],
            options={
                'db_table': 'flavor_votes',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('user_region_snapshot', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='items.item')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='interactions.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.localuser')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.AddConstraint(
            model_name='flavorvote',
            constraint=models.UniqueConstraint(fields=('user', 'flavor_tag'), name='uq_user_flavor_tag'),
        ),
    ]
