# Generated by Django 4.2.25 on 2026-03-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['item', 'created_at'], name='comments_item_id_d30f43_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', 'created_at'], name='comments_user_id_88f50c_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', 'created_at'], name='comments_parent__149355_idx'),
        ),
        migrations.AddIndex(
            model_name='flavortag',
            index=models.Index(fields=['item', 'vote_count'], name='flavor_tags_item_id_517f79_idx'),
        ),
        migrations.AddIndex(
            model_name='flavorvote',
            index=models.Index(fields=['user'], name='flavor_vote_user_id_9a759a_idx'),
        ),
        migrations.AddIndex(
            model_name='flavorvote',
            index=models.Index(fields=['flavor_tag'], name='flavor_vote_flavor__b36205_idx'),
        ),
        migrations.AddConstraint(
            model_name='flavortag',
            constraint=models.UniqueConstraint(fields=('item', 'tag_name'), name='uq_item_tag_name'),
        ),
    ]
