# Generated by Django 4.2.25 on 2026-03-12 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_comment_comments_item_id_d30f43_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='depth',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descendants', to='interactions.comment'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['root', 'created_at'], name='comments_root_id_0df958_idx'),
        ),
    ]
