# Generated by Django 4.2.25 on 2026-03-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'receiver', 'created_at'], name='messages_sender__7f5f42_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'created_at'], name='messages_receive_7d68d6_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['item', 'created_at'], name='messages_item_id_6d9c62_idx'),
        ),
    ]
