# Generated by Django 4.2.25 on 2026-03-12 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_items_categor_22f66e_idx_and_more'),
        ('users', '0003_localuser_password_hash_localuser_phone'),
        ('messaging', '0002_message_messages_sender__7f5f42_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_key', models.CharField(default='global', max_length=64)),
                ('last_seq', models.BigIntegerField(default=0)),
                ('last_message_type', models.CharField(default='text', max_length=20)),
                ('last_message_preview', models.CharField(blank=True, default='', max_length=255)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='items.item')),
                ('participant_high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_high', to='users.localuser')),
                ('participant_low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_low', to='users.localuser')),
            ],
            options={
                'db_table': 'chat_conversations',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.BigIntegerField()),
                ('msg_type', models.CharField(choices=[('text', 'Text'), ('item_card', 'ItemCard'), ('system', 'System'), ('image', 'Image')], default='text', max_length=20)),
                ('content', models.TextField(blank=True, default='')),
                ('client_msg_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='items.item')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='users.localuser')),
            ],
            options={
                'db_table': 'chat_messages',
            },
        ),
        migrations.CreateModel(
            name='ConversationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_seq', models.BigIntegerField(default=0)),
                ('unread_count', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='messaging.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_memberships', to='users.localuser')),
            ],
            options={
                'db_table': 'chat_conversation_members',
                'indexes': [models.Index(fields=['user', 'updated_at'], name='chat_conver_user_id_35187d_idx'), models.Index(fields=['conversation', 'user'], name='chat_conver_convers_eee68c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='conversationmember',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='chat_conv_member_unique'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant_low', 'last_message_at'], name='chat_conver_partici_0d548a_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant_high', 'last_message_at'], name='chat_conver_partici_8a44ab_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['context_key', 'last_message_at'], name='chat_conver_context_92dcf9_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('participant_low', 'participant_high', 'context_key'), name='chat_conv_pair_context_unique'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'seq'], name='chat_messag_convers_87a43f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_0a903c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'created_at'], name='chat_messag_sender__7a605a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['item', 'created_at'], name='chat_messag_item_id_f4cd7a_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(fields=('conversation', 'seq'), name='chat_message_conv_seq_unique'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('client_msg_id', ''), _negated=True), fields=('sender', 'client_msg_id'), name='chat_message_sender_client_unique'),
        ),
    ]
