# Generated by Django 4.2.25 on 2026-03-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=32)),
                ('value', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=64)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'system_options',
            },
        ),
    ]
