# Generated by Django 4.2.25 on 2026-03-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='systemoption',
            index=models.Index(fields=['type', 'sort_order'], name='system_opti_type_8337d3_idx'),
        ),
        migrations.AddIndex(
            model_name='systemoption',
            index=models.Index(fields=['type', 'value'], name='system_opti_type_3322cf_idx'),
        ),
    ]
