# Generated by Django 4.2.25 on 2026-03-13 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchange', '0001_initial'),
        ('items', '0002_item_items_categor_22f66e_idx_and_more'),
        ('users', '0004_localuser_latitude_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('images', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_posts', to='exchange.exchangerequest')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='items.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='users.localuser')),
            ],
            options={
                'db_table': 'community_posts',
            },
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depth', models.PositiveIntegerField(db_index=True, default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.communitycomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.communitypost')),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descendants', to='community.communitycomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to='users.localuser')),
            ],
            options={
                'db_table': 'community_comments',
            },
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['created_at'], name='community_p_created_40799e_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['item', 'created_at'], name='community_p_item_id_ff29aa_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['user', 'created_at'], name='community_p_user_id_5989b4_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['post', 'created_at'], name='community_c_post_id_2fbac0_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['user', 'created_at'], name='community_c_user_id_494cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['parent', 'created_at'], name='community_c_parent__af87b4_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['root', 'created_at'], name='community_c_root_id_a88cd5_idx'),
        ),
    ]
