# Generated by Django 4.2.25 on 2026-03-13 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_localuser_latitude_longitude'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.communitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_post_likes', to='users.localuser')),
            ],
            options={
                'db_table': 'community_post_likes',
                'indexes': [models.Index(fields=['post', 'created_at'], name='community_p_post_id_923e50_idx'), models.Index(fields=['user', 'created_at'], name='community_p_user_id_eacec0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='communitypostlike',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='uq_community_post_like'),
        ),
    ]
