# Generated by Django 4.2.25 on 2026-03-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communitypostlike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitycomment',
            name='audit_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='audit_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='audit_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='audit_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['post', 'is_visible', 'audit_status', 'created_at'], name='community_c_post_id_3cefa1_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['is_visible', 'audit_status', 'created_at'], name='community_p_is_visi_def618_idx'),
        ),
    ]
